In [2]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

datasetPath = "dataset\\data_batch_"

In [3]:
def unpickle(path_batch):
    with open(path_batch, 'rb') as fo:
        batch = pickle.load(fo, encoding='latin1')      
    features = batch['data'].reshape((len(batch['data']), 3, 32, 32)).transpose(0, 2, 3, 1)
    labels = batch['labels']
        
    return features, labels

In [4]:
def get_label_names():
    with open("dataset\\batches.meta", 'rb') as fo:
        data = pickle.load(fo, encoding='latin1')
    return (data['label_names'])

In [5]:
def display_batch_stat(batch_nb):
    features, labels = unpickle(datasetPath + str(batch_nb))
    print("Batch N° %s" % str(batch_nb), "\n")
    print("Number of Samples in batch %s" % str(len(features)), "\n")
    counts =  [[x, labels.count(x)] for x in set(labels)]
    for c in counts:
        print( "%s = %d <=> %.2f %s" % (label_names[c[0]], c[1], (100 * c[1]) / len(features), "%"))
    

In [77]:
display_batch_stat(3)

Batch N° 3 

Number of Samples in batch 10000 

airplane = 994 <=> 9.94 %
automobile = 1042 <=> 10.42 %
bird = 965 <=> 9.65 %
cat = 997 <=> 9.97 %
deer = 990 <=> 9.90 %
dog = 1029 <=> 10.29 %
frog = 978 <=> 9.78 %
horse = 1015 <=> 10.15 %
ship = 961 <=> 9.61 %
truck = 1029 <=> 10.29 %


In [6]:
features, labels = unpickle("dataset\\data_batch_1")
X = features.flatten().reshape(10000, 32*32*3)
Y = np.asarray(labels)
Y_one_hot = tf.one_hot(Y, 10)

print(Y_one_hot)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(10000, 10), dtype=float32)


In [49]:
model = tf.keras.Sequential()
model.add(Dense(1, activation="linear", input_dim=32*32*3))
model.add(Dense(10, activation="softmax", input_dim=1))
model.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X, Y_one_hot, batch_size=10000, verbose=0, epochs=10000)

In [53]:
idx = 1
img = X[idx].reshape(1, 3072)
print(type(model.predict(img)))

label_names = get_label_names()

print (model.predict(img))
res = np.argmax((model.predict(img)))
print(res)
print("predict => " + label_names[res] + " | expected => "  + label_names[Y[idx]])


<class 'numpy.ndarray'>
[[0.19467007 0.20299606 0.03041407 0.03835598 0.01688459 0.02967693
  0.00999344 0.04225935 0.22087492 0.21387456]]
8
predict => ship | expected => truck
