In [14]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf



from tensorflow.keras.losses import sparse_categorical_crossentropy

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.initializers import *
from tensorflow.keras.regularizers import *
from tensorflow.keras.metrics import *
from tensorflow.keras.datasets import *

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

datasetPath = "dataset\\data_batch_"

In [3]:
def unpickle(path_batch):
    with open(path_batch, 'rb') as fo:
        batch = pickle.load(fo, encoding='latin1')      
    features = batch['data'].reshape((len(batch['data']), 3, 32, 32)).transpose(0, 2, 3, 1)
    labels = batch['labels']
        
    return features, labels

In [4]:
def get_label_names():
    with open("dataset\\batches.meta", 'rb') as fo:
        data = pickle.load(fo, encoding='latin1')
    return (data['label_names'])

In [5]:
def display_batch_stat(batch_nb):
    features, labels = unpickle(datasetPath + str(batch_nb))
    print("Batch N° %s" % str(batch_nb), "\n")
    print("Number of Samples in batch %s" % str(len(features)), "\n")
    counts =  [[x, labels.count(x)] for x in set(labels)]
    for c in counts:
        print( "%s = %d <=> %.2f %s" % (label_names[c[0]], c[1], (100 * c[1]) / len(features), "%"))
    

In [77]:
display_batch_stat(3)

Batch N° 3 

Number of Samples in batch 10000 

airplane = 994 <=> 9.94 %
automobile = 1042 <=> 10.42 %
bird = 965 <=> 9.65 %
cat = 997 <=> 9.97 %
deer = 990 <=> 9.90 %
dog = 1029 <=> 10.29 %
frog = 978 <=> 9.78 %
horse = 1015 <=> 10.15 %
ship = 961 <=> 9.61 %
truck = 1029 <=> 10.29 %


In [9]:
features, labels = unpickle("..\\dataset\\data_batch_1")
X = features.flatten().reshape(10000, 32*32*3)
Y = np.asarray(labels)
Y_one_hot = tf.one_hot(Y, 10)

print(Y_one_hot)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(10000, 10), dtype=float32)


In [18]:
model = tf.keras.Sequential()
model.add(Dense(1, activation="linear", input_dim=32*32*3))
model.add(Dense(10, activation="softmax", input_dim=1))
model.compile(optimizer="adam", loss='categorical_crossentropy', metrics=[categorical_accuracy])

model.fit(X, Y_one_hot, batch_size=10000, epochs=10000)

Train on 10000 samples
Epoch 1/10000
10000/10000 [==============================] - 0s 26us/sample - loss: 34.9219 - categorical_accuracy: 0.0953
Epoch 2/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 216.1452 - categorical_accuracy: 0.1033
Epoch 3/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 75.6711 - categorical_accuracy: 0.1043
Epoch 4/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 89.5297 - categorical_accuracy: 0.0926
Epoch 5/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 136.5391 - categorical_accuracy: 0.0936
Epoch 6/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 120.8690 - categorical_accuracy: 0.0937
Epoch 7/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 66.7230 - categorical_accuracy: 0.0936
Epoch 8/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 36.3278 - categorical_accuracy: 0.10

Epoch 68/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 15.8659 - categorical_accuracy: 0.1080
Epoch 69/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 15.7142 - categorical_accuracy: 0.1077
Epoch 70/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 15.5620 - categorical_accuracy: 0.1029
Epoch 71/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 15.5112 - categorical_accuracy: 0.1039
Epoch 72/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 15.2969 - categorical_accuracy: 0.1076
Epoch 73/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 15.2969 - categorical_accuracy: 0.1089
Epoch 74/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 15.0747 - categorical_accuracy: 0.1034
Epoch 75/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 15.0805 - categorical_accuracy: 0.1041
Epoch 76/10000
1

Epoch 135/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 11.1067 - categorical_accuracy: 0.1064
Epoch 136/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 11.0608 - categorical_accuracy: 0.1065
Epoch 137/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 11.0158 - categorical_accuracy: 0.1067
Epoch 138/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 10.9706 - categorical_accuracy: 0.1060
Epoch 139/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 10.9256 - categorical_accuracy: 0.1068
Epoch 140/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 10.8815 - categorical_accuracy: 0.1064
Epoch 141/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 10.8378 - categorical_accuracy: 0.1060
Epoch 142/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 10.7941 - categorical_accuracy: 0.1059
Epoch 14

Epoch 202/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 10.0003 - categorical_accuracy: 0.1114
Epoch 203/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 9.7444 - categorical_accuracy: 0.1039
Epoch 204/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 9.4645 - categorical_accuracy: 0.1139
Epoch 205/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 9.5212 - categorical_accuracy: 0.1044
Epoch 206/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 9.5878 - categorical_accuracy: 0.1130
Epoch 207/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 10.0307 - categorical_accuracy: 0.1018
Epoch 208/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 10.1864 - categorical_accuracy: 0.1105
Epoch 209/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 10.6172 - categorical_accuracy: 0.1002
Epoch 210/10

Epoch 269/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 8.8990 - categorical_accuracy: 0.1039
Epoch 270/10000
10000/10000 [==============================] - 0s 2us/sample - loss: 8.6576 - categorical_accuracy: 0.1153
Epoch 271/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 8.7600 - categorical_accuracy: 0.1050
Epoch 272/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 8.5558 - categorical_accuracy: 0.1158
Epoch 273/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 8.7008 - categorical_accuracy: 0.1052
Epoch 274/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 8.5566 - categorical_accuracy: 0.1152
Epoch 275/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 8.7533 - categorical_accuracy: 0.1040
Epoch 276/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 8.5907 - categorical_accuracy: 0.1146
Epoch 277/10000


Epoch 336/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.7076 - categorical_accuracy: 0.1176
Epoch 337/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.8566 - categorical_accuracy: 0.1061
Epoch 338/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.6773 - categorical_accuracy: 0.1182
Epoch 339/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.8240 - categorical_accuracy: 0.1057
Epoch 340/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.6494 - categorical_accuracy: 0.1184
Epoch 341/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.8002 - categorical_accuracy: 0.1051
Epoch 342/10000
10000/10000 [==============================] - 0s 2us/sample - loss: 7.6292 - categorical_accuracy: 0.1181
Epoch 343/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.7824 - categorical_accuracy: 0.1058
Epoch 344/10000


Epoch 403/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.1102 - categorical_accuracy: 0.1090
Epoch 404/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 6.9492 - categorical_accuracy: 0.1160
Epoch 405/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.0897 - categorical_accuracy: 0.1087
Epoch 406/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 6.9290 - categorical_accuracy: 0.1152
Epoch 407/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.0691 - categorical_accuracy: 0.1086
Epoch 408/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 6.9092 - categorical_accuracy: 0.1147
Epoch 409/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 7.0492 - categorical_accuracy: 0.1091
Epoch 410/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 6.8900 - categorical_accuracy: 0.1146
Epoch 411/10000


Epoch 470/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 6.3537 - categorical_accuracy: 0.1146
Epoch 471/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 6.4831 - categorical_accuracy: 0.1120
Epoch 472/10000
10000/10000 [==============================] - 0s 4us/sample - loss: 6.3373 - categorical_accuracy: 0.1147
Epoch 473/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 6.4663 - categorical_accuracy: 0.1119
Epoch 474/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 6.3209 - categorical_accuracy: 0.1141
Epoch 475/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 6.4496 - categorical_accuracy: 0.1120
Epoch 476/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 6.3046 - categorical_accuracy: 0.1142
Epoch 477/10000
10000/10000 [==============================] - 0s 4us/sample - loss: 6.4330 - categorical_accuracy: 0.1122
Epoch 478/10000


Epoch 537/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.9706 - categorical_accuracy: 0.1129
Epoch 538/10000
10000/10000 [==============================] - 0s 4us/sample - loss: 5.8377 - categorical_accuracy: 0.1153
Epoch 539/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.9562 - categorical_accuracy: 0.1127
Epoch 540/10000
10000/10000 [==============================] - 0s 4us/sample - loss: 5.8237 - categorical_accuracy: 0.1154
Epoch 541/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.9419 - categorical_accuracy: 0.1126
Epoch 542/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.8097 - categorical_accuracy: 0.1154
Epoch 543/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.9277 - categorical_accuracy: 0.1126
Epoch 544/10000
10000/10000 [==============================] - 0s 4us/sample - loss: 5.7959 - categorical_accuracy: 0.1158
Epoch 545/10000


Epoch 604/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.4069 - categorical_accuracy: 0.1145
Epoch 605/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.5155 - categorical_accuracy: 0.1128
Epoch 606/10000
10000/10000 [==============================] - 0s 4us/sample - loss: 5.3947 - categorical_accuracy: 0.1148
Epoch 607/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.5031 - categorical_accuracy: 0.1120
Epoch 608/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.3827 - categorical_accuracy: 0.1149
Epoch 609/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.4907 - categorical_accuracy: 0.1117
Epoch 610/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.3706 - categorical_accuracy: 0.1149
Epoch 611/10000
10000/10000 [==============================] - 0s 4us/sample - loss: 5.4783 - categorical_accuracy: 0.1118
Epoch 612/10000


Epoch 671/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.1304 - categorical_accuracy: 0.1115
Epoch 672/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.0210 - categorical_accuracy: 0.1150
Epoch 673/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.1195 - categorical_accuracy: 0.1117
Epoch 674/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.0104 - categorical_accuracy: 0.1153
Epoch 675/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.1086 - categorical_accuracy: 0.1114
Epoch 676/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 4.9999 - categorical_accuracy: 0.1150
Epoch 677/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 5.0978 - categorical_accuracy: 0.1114
Epoch 678/10000
10000/10000 [==============================] - 0s 3us/sample - loss: 4.9894 - categorical_accuracy: 0.1146
Epoch 679/10000


KeyboardInterrupt: 

In [53]:
idx = 1
img = X[idx].reshape(1, 3072)
print(type(model.predict(img)))

label_names = get_label_names()

print (model.predict(img))
res = np.argmax((model.predict(img)))
print(res)
print("predict => " + label_names[res] + " | expected => "  + label_names[Y[idx]])


<class 'numpy.ndarray'>
[[0.19467007 0.20299606 0.03041407 0.03835598 0.01688459 0.02967693
  0.00999344 0.04225935 0.22087492 0.21387456]]
8
predict => ship | expected => truck


In [15]:
model = tf.keras.Sequential()
model.add(Dense(1, activation="linear", input_dim=32*32*3))
model.add(Dense(10, activation="softmax", input_dim=1))

model.compile(loss=sparse_categorical_crossentropy, optimizer=Adam(), metrics=[sparse_categorical_accuracy])
model.fit(X, Y, batch_size=1000, epochs=100 )

Train on 10000 samples
Epoch 1/100
10000/10000 [==============================] - 0s 28us/sample - loss: 98.7622 - sparse_categorical_accuracy: 0.1054
Epoch 2/100
10000/10000 [==============================] - 0s 7us/sample - loss: 51.4546 - sparse_categorical_accuracy: 0.1047
Epoch 3/100
10000/10000 [==============================] - 0s 6us/sample - loss: 35.3681 - sparse_categorical_accuracy: 0.1055
Epoch 4/100
10000/10000 [==============================] - 0s 6us/sample - loss: 26.0710 - sparse_categorical_accuracy: 0.1003
Epoch 5/100
10000/10000 [==============================] - 0s 5us/sample - loss: 22.0986 - sparse_categorical_accuracy: 0.1047
Epoch 6/100
10000/10000 [==============================] - 0s 6us/sample - loss: 19.3449 - sparse_categorical_accuracy: 0.1142
Epoch 7/100
10000/10000 [==============================] - 0s 5us/sample - loss: 17.5105 - sparse_categorical_accuracy: 0.1132
Epoch 8/100
10000/10000 [==============================] - 0s 6us/sample - loss: 16.579

10000/10000 [==============================] - 0s 5us/sample - loss: 4.7613 - sparse_categorical_accuracy: 0.1269
Epoch 66/100
10000/10000 [==============================] - 0s 5us/sample - loss: 4.9964 - sparse_categorical_accuracy: 0.1219
Epoch 67/100
10000/10000 [==============================] - 0s 5us/sample - loss: 4.7842 - sparse_categorical_accuracy: 0.1246
Epoch 68/100
10000/10000 [==============================] - 0s 5us/sample - loss: 5.0025 - sparse_categorical_accuracy: 0.1209
Epoch 69/100
10000/10000 [==============================] - 0s 5us/sample - loss: 5.1156 - sparse_categorical_accuracy: 0.1245
Epoch 70/100
10000/10000 [==============================] - 0s 4us/sample - loss: 5.0268 - sparse_categorical_accuracy: 0.1224
Epoch 71/100
10000/10000 [==============================] - 0s 4us/sample - loss: 5.1977 - sparse_categorical_accuracy: 0.1220
Epoch 72/100
10000/10000 [==============================] - 0s 6us/sample - loss: 6.6625 - sparse_categorical_accuracy: 0.11